Make the script failing more explicit.

diff --git a/jenkins/integration-tests b/jenkins/integration-tests
--- a/jenkins/integration-tests
+++ b/jenkins/integration-tests
@@ -13,8 +13,15 @@ function cleanUp() {
 
     # Remove the ActiveMQ queue created by these tests.
     echo "Removing the integration test queue from ActiveMQ."
-    sbt 'balboa-agent/it:run-main com.socrata.balboa.agent.RemoveQueue'
-    exit
+    output=$(sbt 'balboa-agent/it:run-main com.socrata.balboa.agent.RemoveQueue' 2>&1)
+    if [[ ! $? -eq 0 ]]; then
+        echo "ERROR: There was a problem removing the queue from the ActiveMQ server."
+        echo "$output"
+    fi
+
+    echo
+    echo "$EXIT_MESSAGE"
+    echo
 }
 # Perform clean up activities under all circumstances (except kill -9) by
 # trapping the 'EXIT' pseudo-signal. Installing this signal handler means the
@@ -66,14 +73,14 @@ BALBOA_AGENT_PID=$!
 
 echo -n "Waiting for balboa-agent to start."
 i=0
-while ! grep "Connected to ActiveMQ broker" $SERVICE_LOG >& /dev/null ; do
+while ! grep "Created Activemq Connection" $SERVICE_LOG >& /dev/null ; do
     sleep 1
     i=$((i + 1))
     echo -n "."
 
     if [[ $i -eq 20 ]]; then
         echo
-        echo "ERROR: It appears that the balboa-agent never started."
+        EXIT_MESSAGE="ERROR: It appears that the balboa-agent never started."
         exit 1
     fi
 done
