Update balboa-http integration tests
Add support for starting a Docker container with a Cassandra instance,
importing the necessary schema and connecting balboa-http to the
instance for the integration tests.

diff --git a/balboa-http/src/it/bash/integration-tests b/balboa-http/src/it/bash/integration-tests
--- a/balboa-http/src/it/bash/integration-tests
+++ b/balboa-http/src/it/bash/integration-tests
@@ -2,7 +2,13 @@
 
 BALBOA_HTTP_PID=0
 
+DB_IMAGE_NAME=socrata-balboa-http-cassandra-${BUILD_NUMBER:-$RANDOM}
+
 function cleanUp() {
+    echo
+    echo "Shutting down the Cassandra Docker container. ($(docker stop $DB_IMAGE_NAME))"
+    echo "Removing the Cassandra Docker container. ($(docker rm -v $DB_IMAGE_NAME))"
+
     if [[ $BALBOA_HTTP_PID -gt 0 ]]; then
         echo "Stopping balboa-http."
         # The balboa-http is running with sbt, so balboa-http itself is
@@ -24,13 +30,20 @@ function cleanUp() {
 # naturally at the end.
 trap cleanUp EXIT
 
-
-function getCassandraSeedNodes() {
-    case $ENVIRONMENT in
-        *)
-            echo "localhost:9042"
-            ;;
-    esac
+function waitForSuccess() {
+  i=0
+  while ! ( "$@" ) ; do
+    sleep 1
+    ((i++))
+    if [[ $i -eq 300 ]]; then
+      echo
+      echo "Timed out waiting for service to become healthy."
+      echo
+      return 1
+    fi
+  done
+  echo
+  return 0
 }
 
 function getAvailableServicePort() {
@@ -57,17 +70,69 @@ echo "************************************************************"
 echo " Starting balboa-http integration tests."
 echo
 
+if uname -a | grep Darwin >& /dev/null ; then
+  # On a Mac, look for the IP address of the VM docker-machine is using to run
+  # Docker containers.
+  eval $(docker-machine env)
+  dockerHost=$(docker-machine ip)
+  if [[ ! $? -eq 0 ]]; then
+    echo "Could not get the IP address of an active docker-machine instance."
+    echo "Use 'docker-machine ls' to confirm there is an active host."
+    exit 1
+  fi
+else
+  # On Linux, look for the IP address associated with the 'docker' interface.
+  dockerHost=$(/sbin/ifconfig docker0 | sed '/inet addr:/!d;s|.*inet addr:\([^ ]*\).*|\1|')
+  if [[ -z $dockerHost ]]; then
+    echo "Could not find a docker network interface. Is Docker installed?"
+    exit 1
+  fi
+fi
+
+# Process the Cassandra schema template and replace the necessary variables
+# with useful values.
+SCHEMA_DIR=target/balboa-http-schema
+mkdir -p $SCHEMA_DIR
+sed "
+    s|{{datacenter-name}}|datacenter1|;
+    s|{{replication-factor}}|1|;
+" etc/balboa-cassandra.cql > ${SCHEMA_DIR}/balboa-cassandra.cql
+
+docker run \
+  -d \
+  --name $DB_IMAGE_NAME \
+  -p 9042/tcp \
+  -p 9160/tcp \
+  -v $(pwd)/${SCHEMA_DIR}:/balboa-schema \
+  cassandra:2.1
+
+dbServerIp=$dockerHost
+dbPort=$(docker inspect --format '{{ (index (index .NetworkSettings.Ports "9042/tcp") 0).HostPort }}' $DB_IMAGE_NAME)
+
+echo "Looking for the database on $dbServerIp:$dbPort"
+if ! waitForSuccess nc -w 1 $dbServerIp $dbPort ; then
+  echo "Problem starting the database image."
+  echo "============================== Docker Logs: Database Image =============================="
+  docker logs $DB_IMAGE_NAME
+  exit 1
+fi
+echo "Database is started."
+
+# Install the schema on the database.
+echo "Installing the schema in the Cassandra database."
+if ! docker exec $DB_IMAGE_NAME cassandra-cli -f /balboa-schema/balboa-cassandra.cql ; then
+  echo "Failed to install the Cassandra schema."
+  exit 1
+fi
+
 ORIGINAL_PROPERTIES_FILE=balboa-http/src/main/resources/config/config.properties
 TEST_PROPERTIES_FILE="target/balboa-http-integrationtest-config-$$.properties"
 
-export CASSANDRAS=$(getCassandraSeedNodes)
+export CASSANDRAS=$dbServerIp:$dbPort
 echo "Writing temporary properties file to '$TEST_PROPERTIES_FILE'."
 sed "
     /^ *cassandra.servers[ =]/s|=.*|= $CASSANDRAS|
 " $ORIGINAL_PROPERTIES_FILE > $TEST_PROPERTIES_FILE
-
-SERVICE_LOG=target/balboa-http-$$.log
-echo "Writing service log to '$SERVICE_LOG'"
 
 # By adding a pre-compile step, the length of the compile does not add to the
 # timeout around waiting for the service to start up. Using a separate step
@@ -77,31 +142,36 @@ if ! sbt balboa-http/compile ; then
     exit 1
 fi
 
-SERVICE_PORT=$(getAvailableServicePort)
+# Make sure the log file exists so that if there will be no race condition
+# where we grep for the success message before sbt gets started.
+SERVICE_LOG=target/balboa-http-$$.log
+touch $SERVICE_LOG
+echo "Writing service log to '$SERVICE_LOG'"
+
 # The dataset-of-datasets integration tests build a dockerized service for
 # doing the testing, but making the dockerized service consumes a significant
 # portion of the time for executing the integration tests. These tests run the
 # service using sbt in the background to try to execute integration tests
 # faster.
+SERVICE_PORT=$(getAvailableServicePort)
 sbt "balboa-http/run $SERVICE_PORT" "-Dbalboa.config=$TEST_PROPERTIES_FILE" >& $SERVICE_LOG &
 BALBOA_HTTP_PID=$!
 
-echo -n "Waiting for balboa-http to start on port $SERVICE_PORT."
-i=0
-while ! grep "Starting balboa-http service" $SERVICE_LOG >& /dev/null ; do
-    sleep 1
-    i=$((i + 1))
-    echo -n "."
-
-    if [[ $i -eq 20 ]]; then
-        echo
-        EXIT_MESSAGE="ERROR: It appears that the balboa-http never started."
-        exit 1
-    fi
-done
-echo
+echo "Waiting for balboa-http to start on port $SERVICE_PORT."
+if ! waitForSuccess grep -q 'Starting balboa-http service' $SERVICE_LOG ; then
+  echo "Problem starting balboa-http service."
+  echo "============================== balboa-http service logs  =============================="
+  cat $SERVICE_LOG
+  exit 1
+fi
 echo "balboa-http service is started."
 
 echo "Running integration tests."
 export SERVICE_PORT  # So it is available for integration test configuration.
 sbt balboa-http/it:test
+rc=$?
+if [[ ! $rc -eq 0 ]]; then
+  echo "============================== balboa-http service logs  =============================="
+  cat $SERVICE_LOG
+fi
+exit $rc
